### ISSUE TITLE
`docr add crystal 1.7.3` throws ".config/docr/versions.json: permission denied"

### ISSUE THREAD

**Issue by mdwagner** [devnote-dev/docr#4]
It looks like `~/.config/docr` is being created with a permission of `0100`. I've tried changing it to 775 or something, but it just switches it back.

**Comment by devnote-dev** [comment]
What version of Docr are you using? I believe that should have been fixed in v0.1.1.

**Comment by mdwagner** [comment]
I went to the release page on the README, and downloaded amd64 version. But now I see it's using 0.1.0.

**Comment by mdwagner** [comment]
Hmm. So, the release page for 0.1.1 is downloading for 0.1.0

Fresh download from 0.1.1 page:
```
➤ ./docr_linux_amd64 version
Docr version 0.1.0 c17fc5d5 (2023-04-25)
```

**Comment by devnote-dev** [comment]
Ah I see, something may have gone wrong with the release CI. I'll look into it ASAP, in the meantime you'll have to build Docr from source, it's relatively straightforward but feel free to message me if you need help.

**Comment by devnote-dev** [comment]
This should be fixed now, I think the release CI just needed to be re-ran (might have been cancelled the first time, not sure):
https://github.com/devnote-dev/docr/releases/tag/v0.1.2
